// js/data.js

const translations = {
    en: {
        // General & Header
        title: 'BusGo - Bus Ticket Booking',
        login_btn: 'Login',
        logout_btn: 'Logout',
        my_account: 'My Account',

        // Home Page
        hero_title: 'Your Journey, Your Way',
        hero_subtitle: 'Effortless Bus Ticket Booking at Your Fingertips',
        from_label: 'From',
        to_label: 'To',
        date_label: 'Date',
        search_buses: 'Search',
        same_location_text: 'The "From" and "To" locations cannot be the same. Please choose different locations.',

        // Buses Page
        filters: 'Filters',
        price_range: 'Price Range',
        bus_type: 'Bus Type',
        departure_time: 'Departure Time',
        rating: 'Rating',
        clear_filters: 'Clear Filters',
        no_buses_match_filters: 'No buses match your current filters.',
        before_6am: 'Before 6 AM',
        morning: '6 AM - 12 PM',
        afternoon: '12 PM - 6 PM',
        night: 'After 6 PM',
        rating_4_plus: '4★ & above',
        rating_3_plus: '3★ & above',
        rating_any: 'Any',
        book_seats_btn: 'Book Seats',

        // Booking Page
        select_seats_title: 'Select Your Seats',
        available_seat: 'Available',
        selected_seat: 'Selected',
        booked_male_seat: 'Booked (Male)',
        booked_female_seat: 'Booked (Female)',
        reserved_for_female: 'Reserved for Female',
        booking_summary: 'Booking Summary',
        bus: 'Bus',
        route: 'Route',
        selected_seats: 'Selected Seats',
        total: 'Total',
        passenger_details: 'Passenger Details',
        adults: 'Number of Adults',
        children: 'Number of Children (5-11 yrs)',
        mismatch_message: 'The number of passengers must match the number of selected seats.',
        child_fare_note: "Note: Children aged 5-11 get a 50% discount. Children above 130cm height will be charged full fare.",
        single_child_booking_error: "Single child booking is not allowed for safety reasons. Please add at least one adult.",
        age_mismatch_error: "The number of adults and children based on the ages you entered does not match the counts from the booking page. Please correct the ages.",
        gender_mismatch_error: "A selected seat is reserved for a specific gender. Please check your passenger details.",

        // Details Page
        aadhaar_number: 'Aadhaar Number',
        confirm_booking: 'Confirm Booking',
        
        // Payment Page
        payment_methods: "Payment Methods",
        credit_debit_cards: "Credit / Debit Cards",
        net_banking: "Net Banking",
        upi: "UPI",
        wallets: "Wallets",
        upi_qr: "UPI QR",
        card_number: "Card Number",
        expiration_date: "Expiration date",
        security_code: "Security code",
        card_holder_name: "Card holder name",
        search_by_bank: "Search by bank name",
        top_banks: "Top banks",
        show_qr: "Show QR",
        or: "Or",
        enter_upi_id: "Enter your UPI ID",
        top_wallets: "Top wallets",
        scan_qr_code: "Scan the QR code",
        use_upi_app: "Use your UPI app to make your payment.",
        code_expires_in: "Code expires in",
        summary: "Summary",
        order_id: "Order ID",
        total_amount: "Total Amount",
        pay_now: "Pay Now",
        dos_and_donts: "Dos & Don'ts",
        digital_wallets: "Digital Wallets",
        dos: "DOs:",
        donts: "DON'Ts:",
        set_strong_password: "Set a strong password/PIN for your phone and mobile wallet app.",
        download_verified_app: "Download a verified app from the Play Store/App Store.",
        install_antivirus: "Install an anti-virus to ensure your phone is protected.",
        logout_after_transaction: "Exit the app or log out after every transaction.",
        dont_use_same_password: "Do not use the same password for all wallets.",
        dont_download_third_party: "Do not download third-party applications and enter your details without authentication.",
        avoid_unidentified_qr: "Avoid scanning unidentified QR codes.",
        credit_debit_cards_dos_donts: "Credit and Debit cards",
        opt_for_notifications: "Opt for getting mobile notifications every time a transaction is made.",
        discard_receipts: "Properly discard receipts or statements with your details on them.",
        choose_secure_pin: "Choose a secure PIN and stay away from predictable ones such as common dates like birthdays etc.",
        dont_disclose_cvv: "Do not disclose your CVV or PIN to anybody. The bank will never ask for personal information over a call.",
        dont_ignore_alerts: "Do not ignore a transaction alert on SMS. Contact your bank immediately.",
        avoid_saving_card_details: "Avoid saving your card details on online platforms.",
        what_to_do_in_case_of_cyber_fraud: "What to do in case of cyber-fraud?",
        despite_strong_security: "Despite strong digital payment security systems, cyber-attacks and frauds can still happen in some instances.",
        in_such_cases: "In such cases:Immediately reach out to your bank.",
        transaction_failure_note: "Note: In case of transaction failure after making payment, please check your Booking History and verify the booking status of your ticket/booking.",
        
        // Account Page
        my_bookings: 'My Bookings',
        booking_id_is: 'Your booking ID is',
        no_history: 'You have no booking history yet.',
        seats: 'Seats',
        departure: 'Departure',
        passengers: 'Passengers',
        male: 'Male',
        female: 'Female',
        child: 'Child',
        aadhaar: 'Aadhaar',
        refund_rules: 'Refund Rules',
        refund_amount: 'Refund Amount',
        cancellation_charge: 'Cancellation Charge',
        ticket_cancelled: 'Cancelled',
        confirm_cancellation: 'Are you sure you want to cancel this ticket?',
        cancellation_successful: 'Your ticket has been successfully cancelled.',
        booking_status: 'Status',
        status_confirmed: 'Confirmed',
        status_expired: "Expired",
        rate_now: "Rate Now",
        rated: "Rated",
        rate_journey_title: "How was your journey?",
        submit_review: "Submit Review",
        print_ticket: 'Print Ticket',
        cancel_ticket: 'Cancel Ticket',
        confirm_cancellation_title: 'Confirm Cancellation',
        confirm_cancellation_body: 'Are you sure you want to cancel this ticket? The refund details are as follows:',
        total_fare: 'Total Fare',
        confirm: 'Confirm',
        go_back: 'Go Back',
        refund_policy_details: `<h3 class="text-lg font-bold mb-2">Refund Policy for E-Tickets</h3><ul class="list-disc list-inside text-left space-y-2 text-sm"><li><strong>Before 48 hours of departure:</strong> 10% deduction of fare.</li><li><strong>Between 24 & 48 hours of departure:</strong> 20% deduction of fare.</li><li><strong>Between 1 & 24 hours of departure:</strong> 25% deduction of fare.</li><li>Cancellation is allowed only up to <strong>one (1) hour</strong> before the scheduled departure.</li><li>Reservation fees and other charges are non-refundable.</li><li>All refunds will be processed to the source account within 14 bank working days.</li><li>If a service is cancelled by BusGo, a full refund will be processed after receiving a claim from the customer.</li></ul>`,
        
        // Auth & Popups
        please_login_to_book: 'Please log in to book seats.',
        ok: 'OK',
        booking_confirmed: 'Booking confirmed!',
        login_with_email_phone: 'Login with Email or Phone No',
        email_or_phone: 'Email or Phone Number',
        password: 'Password',
        dont_have_account: "You don't have an account?",
        register_now: 'Register Now',
        create_account: 'Create Your Account',
        full_name: 'Full Name',
        phone_no: 'Phone Number',
        email_optional: 'Email (Optional)',
        confirm_password: 'Confirm Password',
        captcha: 'CAPTCHA',
        enter_captcha: 'Enter the code above',
        register: 'Register',
        passwords_do_not_match: 'Passwords do not match!',
        captcha_mismatch: 'CAPTCHA code is incorrect.',
        registration_successful: 'Registration successful! You are now logged in.',
        user_not_found: 'User not found. Please check your credentials or register.',
        login_successful: 'Login successful!',
        login_failed_password: 'Login failed. The password you entered is incorrect.',
        phone_already_registered: 'This phone number is already registered.',
        email_already_registered: 'This email is already registered.',

        apply_coupon: "Apply Coupon",
        apply: "Apply",
        coupon_applied: "Coupon applied successfully!",
        invalid_coupon: "Invalid or expired coupon code.",
        coupon_already_used: "This coupon has already been used.",
        discount: "Discount",
        remove_coupon: "Remove",
        coupon_success_title: "Yay!!!",
        you_saved: "You have saved upto",

        // Footer
        busgo_all_rights: 'BusGo. All rights reserved.',
        project_motto: 'Developed by Jeba Shalom',
    },
    ta: {
        // General & Header
        title: 'பஸ் கோ - பஸ் டிக்கெட் முன்பதிவு',
        login_btn: 'உள்நுழைக',
        logout_btn: 'வெளியேறு',
        my_account: 'எனது கணக்கு',

        // Home Page
        hero_title: 'உங்கள் பயணம், உங்கள் வழி',
        hero_subtitle: 'உங்கள் விரல் நுனியில் எளிதான பஸ் டிக்கெட் முன்பதிவு',
        from_label: 'புறப்படுமிடம்',
        to_label: 'சேருமிடம்',
        date_label: 'தேதி',
        search_buses: 'தேடு',
        same_location_text: '"இருந்து" மற்றும் "க்கு" இடங்கள் ஒன்றாக இருக்க முடியாது. தயவுசெய்து வெவ்வேறு இடங்களைத் தேர்ந்தெடுக்கவும்.',

        // Buses Page
        filters: 'வடிகட்டிகள்',
        price_range: 'விலை வரம்பு',
        bus_type: 'பஸ் வகை',
        departure_time: 'புறப்படும் நேரம்',
        rating: 'மதிப்பீடு',
        clear_filters: 'வடிகட்டிகளை அழி',
        no_buses_match_filters: 'உங்கள் தற்போதைய வடிப்பான்களுடன் எந்த பஸ்களும் பொருந்தவில்லை.',
        before_6am: 'காலை 6 மணிக்குள்',
        morning: 'காலை 6 - மதியம் 12',
        afternoon: 'மதியம் 12 - மாலை 6',
        night: 'மாலை 6 மணிக்குப் பிறகு',
        rating_4_plus: '4★ மற்றும் அதற்கு மேல்',
        rating_3_plus: '3★ மற்றும் அதற்கு மேல்',
        rating_any: 'ஏதேனும்',
        book_seats_btn: 'இருக்கைகளை முன்பதிவு செய்',

        // Booking Page
        select_seats_title: 'உங்கள் இருக்கைகளைத் தேர்ந்தெடுக்கவும்',
        available_seat: 'கிடைக்கிறது',
        selected_seat: 'தேர்ந்தெடுக்கப்பட்டது',
        booked_male_seat: 'முன்பதிவு செய்யப்பட்டது (ஆண்)',
        booked_female_seat: 'முன்பதிவு செய்யப்பட்டது (பெண்)',
        reserved_for_female: 'பெண்களுக்கு ஒதுக்கப்பட்டது',
        booking_summary: 'முன்பதிவு சுருக்கம்',
        bus: 'பஸ்',
        route: 'வழித்தடம்',
        selected_seats: 'தேர்ந்தெடுக்கப்பட்ட இருக்கைகள்',
        total: 'மொத்தம்',
        passenger_details: 'பயணிகள் விவரங்கள்',
        adults: 'பெரியவர்களின் எண்ணிக்கை',
        children: 'குழந்தைகளின் எண்ணிக்கை (5-11 வயது)',
        mismatch_message: 'பயணிகளின் எண்ணிக்கை தேர்ந்தெடுக்கப்பட்ட இருக்கைகளின் எண்ணிக்கையுடன் பொருந்த வேண்டும்.',
        child_fare_note: "குறிப்பு: 5-11 வயதுக்குட்பட்ட குழந்தைகளுக்கு 50% தள்ளுபடி. 130 செ.மீ.க்கு மேல் உயரமுள்ள குழந்தைகளுக்கு முழு கட்டணம் வசூலிக்கப்படும்.",
        single_child_booking_error: "பாதுகாப்பு காரணங்களுக்காக தனியாக குழந்தை முன்பதிவு அனுமதிக்கப்படாது. தயவுசெய்து ஒரு பெரியவரையாவது சேர்க்கவும்.",
        age_mismatch_error: "நீங்கள் உள்ளிட்ட வயதுகளின் அடிப்படையில் பெரியவர்கள் மற்றும் குழந்தைகளின் எண்ணிக்கை, முன்பதிவுப் பக்கத்தில் உள்ள எண்ணிக்கைகளுடன் பொருந்தவில்லை. దయచేసి వయస్సులను సరిచేయండి.",
        gender_mismatch_error: "தேர்ந்தெடுக்கப்பட்ட இருக்கை ஒரு குறிப்பிட்ட பாலினத்திற்காக ஒதுக்கப்பட்டுள்ளது. உங்கள் பயணிகள் விவரங்களைச் சரிபார்க்கவும்.",

        // Details Page
        aadhaar_number: 'ஆதார் எண்',
        confirm_booking: 'முன்பதிவை உறுதி செய்',
        
        // Payment Page
        payment_methods: "பணம் செலுத்தும் முறைகள்",
        credit_debit_cards: "கிரெடிட் / டெபிட் கார்டுகள்",
        net_banking: "நிகர் வங்கி",
        upi: "UPI",
        wallets: "வாலெட்டுகள்",
        upi_qr: "UPI QR",
        card_number: "அட்டை எண்",
        expiration_date: "காலாவதி தேதி",
        security_code: "பாதுகாப்புக் குறியீடு",
        card_holder_name: "அட்டைதாரர் பெயர்",
        search_by_bank: "வங்கிப் பெயரில் தேடவும்",
        top_banks: "சிறந்த வங்கிகள்",
        show_qr: "QR காட்டு",
        or: "அல்லது",
        enter_upi_id: "உங்கள் UPI ஐடியை உள்ளிடவும்",
        top_wallets: "சிறந்த வாலெட்டுகள்",
        scan_qr_code: "QR குறியீட்டை ஸ்கேன் செய்யவும்",
        use_upi_app: "பணம் செலுத்த உங்கள் UPI பயன்பாட்டைப் பயன்படுத்தவும்.",
        code_expires_in: "குறியீடு காலாவதியாகிறது",
        summary: "சுருக்கம்",
        order_id: "ஆர்டர் ஐடி",
        total_amount: "மொத்த தொகை",
        pay_now: "இப்போது செலுத்துங்கள்",
        dos_and_donts: "செய்ய வேண்டியவை மற்றும் செய்யக்கூடாதவை",
        digital_wallets: "டிஜிட்டல் வாலெட்டுகள்",
        dos: "செய்ய வேண்டியவை:",
        donts: "செய்யக்கூடாதவை:",
        set_strong_password: "உங்கள் தொலைபேசி மற்றும் மொபைல் வாலட் பயன்பாட்டிற்கு வலுவான கடவுச்சொல்/பின்னை அமைக்கவும்.",
        download_verified_app: "Play Store/App Store இலிருந்து சரிபார்க்கப்பட்ட பயன்பாட்டைப் பதிவிறக்கவும்.",
        install_antivirus: "உங்கள் தொலைபேசி பாதுகாக்கப்படுவதை உறுதிசெய்ய வைரஸ் தடுப்பு மருந்துகளை நிறுவவும்.",
        logout_after_transaction: "ஒவ்வொரு பரிவர்த்தனைக்குப் பிறகும் பயன்பாட்டிலிருந்து வெளியேறவும் அல்லது வெளியேறவும்.",
        dont_use_same_password: "எல்லா வாலெட்டுகளுக்கும் ஒரே கடவுச்சொல்லைப் பயன்படுத்த வேண்டாம்.",
        dont_download_third_party: "மூன்றாம் தரப்பு பயன்பாடுகளைப் பதிவிறக்கம் செய்து அங்கீகாரம் இல்லாமல் உங்கள் விவரங்களை உள்ளிட வேண்டாம்.",
        avoid_unidentified_qr: "அடையாளம் தெரியாத QR குறியீடுகளை ஸ்கேன் செய்வதைத் தவிர்க்கவும்.",
        credit_debit_cards_dos_donts: "கிரெடிட் மற்றும் டெபிட் கார்டுகள்",
        opt_for_notifications: "ஒவ்வொரு முறையும் ஒரு பரிவர்த்தனை செய்யப்படும்போது மொபைல் அறிவிப்புகளைப் பெறுவதைத் தேர்வுசெய்யவும்.",
        discard_receipts: "உங்கள் விவரங்களுடன் ரசீதுகள் அல்லது அறிக்கைகளை முறையாக நிராகரிக்கவும்.",
        choose_secure_pin: "பாதுகாப்பான பின்னைத் தேர்வுசெய்து, பிறந்தநாள் போன்ற பொதுவான தேதிகள் போன்ற கணிக்கக்கூடியவற்றிலிருந்து விலகி இருங்கள்.",
        dont_disclose_cvv: "உங்கள் CVV அல்லது PIN ஐ யாரிடமும் வெளியிட வேண்டாம். வங்கி ஒருபோதும் அழைப்பின் மூலம் தனிப்பட்ட தகவல்களைக் கேட்காது.",
        dont_ignore_alerts: "எஸ்எம்எஸ் இல் பரிவர்த்தனை எச்சரிக்கையை புறக்கணிக்காதீர்கள். உடனடியாக உங்கள் வங்கியைத் தொடர்பு கொள்ளுங்கள்.",
        avoid_saving_card_details: "ஆன்லைன் தளங்களில் உங்கள் அட்டை விவரங்களைச் சேமிப்பதைத் தவிர்க்கவும்.",
        what_to_do_in_case_of_cyber_fraud: "சைபர் மோசடி ஏற்பட்டால் என்ன செய்வது?",
        despite_strong_security: "வலுவான டிஜிட்டல் கட்டண பாதுகாப்பு அமைப்புகள் இருந்தபோதிலும், சில சமயங்களில் சைபர் தாக்குதல்கள் மற்றும் மோசடிகள் இன்னும் நிகழலாம்.",
        in_such_cases: "அത്തരം சந்தர்ப்பங்களில்: உடனடியாக உங்கள் வங்கியை அணுகவும்.",
        transaction_failure_note: "குறிப்பு: பணம் செலுத்திய பிறகு பரிவர்த்தனை தோல்வியுற்றால், உங்கள் முன்பதிவு வரலாற்றைச் சரிபார்த்து, உங்கள் டிக்கெட்/முன்பதிவின் முன்பதிவு நிலையைச் சரிபார்க்கவும்.",
        
        // Account Page
        my_bookings: 'எனது முன்பதிவுகள்',
        booking_id_is: 'உங்கள் முன்பதிவு எண்',
        no_history: 'உங்களுக்கு இதுவரை முன்பதிவு வரலாறு இல்லை.',
        seats: 'இருக்கைகள்',
        departure: 'புறப்பாடு',
        passengers: 'பயணிகள்',
        male: 'ஆண்',
        female: 'பெண்',
        child: 'குழந்தை',
        aadhaar: 'ஆதார்',
        refund_rules: 'பணம் திரும்பப் பெறும் விதிகள்',
        refund_amount: 'திரும்பப்பெறும் தொகை',
        cancellation_charge: 'ரத்து கட்டணம்',
        ticket_cancelled: 'ரத்து செய்யப்பட்டது',
        confirm_cancellation: 'இந்த டிக்கெட்டை ரத்து செய்ய விரும்புகிறீர்களா?',
        cancellation_successful: 'உங்கள் டிக்கெட் வெற்றிகரமாக ரத்து செய்யப்பட்டது.',
        booking_status: 'நிலை',
        status_confirmed: 'உறுதி செய்யப்பட்டது',
        status_expired: "காலாவதியானது",
        rate_now: "மதிப்பிடுக",
        rated: "மதிப்பிடப்பட்டது",
        rate_journey_title: "உங்கள் பயணம் எப்படி இருந்தது?",
        submit_review: "மதிப்பீட்டைச் சமர்ப்பி",
        print_ticket: 'டிக்கெட் அச்சிடுக',
        cancel_ticket: 'டிக்கெட்டை ரத்துசெய்',
        confirm_cancellation_title: 'ரத்து செய்வதை உறுதிப்படுத்தவும்',
        confirm_cancellation_body: 'இந்த டிக்கெட்டை ரத்து செய்ய விரும்புகிறீர்களா? திரும்பப்பெறும் விவரங்கள் பின்வருமாறு:',
        total_fare: 'மொத்த கட்டணம்',
        confirm: 'உறுதி செய்',
        go_back: 'திரும்பிச் செல்',
        refund_policy_details: `<h3 class="text-lg font-bold mb-2">மின்-டிக்கெட்டுகளுக்கான பணம் திரும்பப் பெறும் கொள்கை</h3><ul class="list-disc list-inside text-left space-y-2 text-sm"><li><strong>புறப்படுவதற்கு 48 மணி நேரத்திற்கு முன்:</strong> கட்டணத்தில் 10% பிடித்தம்.</li><li><strong>புறப்படுவதற்கு 24 முதல் 48 மணி நேரத்திற்குள்:</strong> கட்டணத்தில் 20% பிடித்தம்.</li><li><strong>புறப்படுவதற்கு 1 முதல் 24 மணி நேரத்திற்குள்:</strong> கட்டணத்தில் 25% பிடித்தம்.</li><li>பஸ் புறப்படுவதற்கு <strong>ஒரு (1) மணி நேரம்</strong> முன்பு வரை மட்டுமே ரத்து செய்ய அனுமதிக்கப்படும்.</li><li>முன்பதிவு கட்டணம் மற்றும் பிற கட்டணங்கள் திரும்பப் பெறப்படாது.</li><li>அனைத்து பணமும் 14 வங்கி வேலை நாட்களுக்குள் மூல கணக்கிற்குத் திருப்பித் தரப்படும்.</li><li>BusGo சேவையை ரத்து செய்தால், வாடிக்கையாளரிடமிருந்து கோரிக்கை கடிதம் பெற்ற பிறகு முழுப் பணமும் திருப்பித் தரப்படும்.</li></ul>`,

        // Auth & Popups
        please_login_to_book: 'இருக்கைகளை முன்பதிவு செய்ய உள்நுழையவும்.',
        ok: 'சரி',
        booking_confirmed: 'முன்பதிவு உறுதி செய்யப்பட்டது!',
        login_with_email_phone: 'மின்னஞ்சல் அல்லது தொலைபேசி எண் மூலம் உள்நுழைக',
        email_or_phone: 'மின்னஞ்சல் அல்லது தொலைபேசி எண்',
        password: 'கடவுச்சொல்',
        dont_have_account: 'உங்களிடம் கணக்கு இல்லையா?',
        register_now: 'இப்போதே பதிவு செய்யவும்',
        create_account: 'உங்கள் கணக்கை உருவாக்கவும்',
        full_name: 'முழு பெயர்',
        phone_no: 'தொலைபேசி எண்',
        email_optional: 'மின்னஞ்சல் (விருப்பத்தேர்வு)',
        confirm_password: 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
        captcha: 'கேப்ட்சா',
        enter_captcha: 'மேலே உள்ள குறியீட்டை உள்ளிடவும்',
        register: 'பதிவு செய்',
        passwords_do_not_match: 'கடவுச்சொற்கள் பொருந்தவில்லை!',
        captcha_mismatch: 'கேப்ட்சா குறியீடு தவறானது.',
        registration_successful: 'பதிவு வெற்றி பெற்றது! நீங்கள் இப்போது உள்நுழைந்துள்ளீர்கள்.',
        user_not_found: 'பயனர் கண்டுபிடிக்கப்படவில்லை. உங்கள் சான்றுகளைச் சரிபார்க்கவும் அல்லது பதிவு செய்யவும்.',
        login_successful: 'உள்நுழைவு வெற்றி பெற்றது!',
        login_failed_password: 'உள்நுழைவு தோல்வியடைந்தது. நீங்கள் உள்ளிட்ட கடவுச்சொல் தவறானது.',
        phone_already_registered: 'இந்த தொலைபேசி எண் ஏற்கனவே பதிவு செய்யப்பட்டுள்ளது.',
        email_already_registered: 'இந்த மின்னஞ்சல் ஏற்கனவே பதிவு செய்யப்பட்டுள்ளது.',

        apply_coupon: "கூப்பனைப் பயன்படுத்து",
        apply: "பயன்படுத்து",
        coupon_applied: "கூப்பன் வெற்றிகரமாகப் பயன்படுத்தப்பட்டது!",
        invalid_coupon: "தவறான அல்லது காலாவதியான கூப்பன் குறியீடு.",
        coupon_already_used: "இந்த கூப்பன் ஏற்கனவே பயன்படுத்தப்பட்டது.",
        discount: "தள்ளுபடி",
        remove_coupon: "நீக்கு",
        coupon_success_title: "யே!!!",
        you_saved: "நீங்கள் சேமித்துள்ளீர்கள்",
        
        // Footer
        busgo_all_rights: 'பஸ் கோ. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
        project_motto: 'ஜெபா ஷாலோம் அவர்களால் உருவாக்கப்பட்டது',
    }
};

const coupons = {
    "FIRSTBUS": 15, // 15% off
    "BUSGO20": 20, // 20% off
    "SAVE10": 10   // 10% off
};

const CITIES = [
    "ALANKULAM", "ANNAVASAL", "ARANI", "ARANTHANGI", "ARIMALAM", "ARUPPUKOTTAI",
    "AVUDAIYAR KOIL", "BANGALORE", "BATLAGUNDU", "BODI", "CHENGANACHERY", "CHENGODE",
    "CHENNAI", "CHENNAI (Via Chittoor)", "CHIDAMBARAM", "CHINNALAPATTI", "CHOTTANIKARAI",
    "COIMBATORE", "CUDDALORE", "CUMBUM", "DEVAKOTTAI", "DEVAPATTINAM", "DHARAPURAM",
    "DHARMAPURI", "DINDIGUL", "ERNAKULAM", "ERODE", "ERUMELY", "GALLE", "GOBI",
    "GURUVAYUR", "HOSUR", "IDAPPADI", "ILAYANKUDI", "KADAIYANALLUR", "KALAIYAR KOIL",
    "KALPETTA", "KAMBAN", "KAMUTHI", "KANNIYAKUMARI", "KARAIKAL", "KARAIKUDI", "KARUR",
    "KATPADI", "KAYALPATTINAM", "KEERAMANGALAM", "KILAKARAI", "KODAIKANAL", "KOTTARAKARAI",
    "KOTTAIYUR", "KOTTAYAM", "KOVILPATTI", "KRISHNAGIRI", "KULASEKARAM", "KUMBAKONAM",
    "KUMILY", "KUNNAM", "KUNRATHUR", "KUZHITHURAI", "MADURAI", "MANAMADURAI", "MANNARGUDI",
    "MARTHANDAM", "MAYILADUTHURAI", "METTUPALAYAM", "METTUR", "MUDUKULATHUR", "MUNNAR",
    "MYSORE", "NAGAPATTINAM", "NAGERCOIL", "NAMAKKAL", "NAZARETH", "NEYVELI T.S",
    "NILAKOTTAI", "OOTY", "ORATHANADU", "PALACODE", "PALAKKADU", "PALANI", "PALLAPATTI",
    "PAMBA", "PANNAIPURAM", "PANRUTI", "PAPANASAM", "PARAMAKUDI", "PATTUKOTTAI",
    "PERAVURANI", "PERIYAKULAM", "POLLACHI", "PUDUCHERRY", "PUDUKOTTAI", "PULIYANKUDI",
    "RAJAPALAYAM", "RAMESWARAM", "RASIPURAM", "SALEM", "SANKARANKOIL", "SATHYAMANGALAM",
    "SATTUR", "SAYALKUDI", "SEMBANAR KOIL", "SENGOTTAI", "SHENCOTTAH", "SIRKALI",
    "SIRUSERI", "SIVAGANGAI", "SIVAKASI", "SULTHAN BATHERY", "TENKASI", "THANJAVUR",
    "THARAIKUDI", "THENI", "THIRUCHENDUR", "THIRUKADAIYUR", "THIRUKKUVALAI",
    "THIRUMAYAM", "THIRUNALLAR", "THIRUVADANAI", "THIRUVAIYARU", "THIRUVARUR",
    "THISAYANVILAI", "THITTUVILAI", "THONDI", "THRISSUR", "TIRUCHIRAPALLI",
    "TIRUNELVELI", "TIRUPATHI", "TIRUPPUR", "TIRUVANNAMALAI", "TRIVANDRUM",
    "TUTICORIN", "UDANKUDI", "UDUMALPET", "USILAMPATTI", "VEDARANYAM", "VEDASANDUR",
    "VELANKANNI"
];